// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoMsFF09fuhCdTNjIRYLHq4NUYxzeq3Wg',
    appId: '1:701813741399:web:abb9e3e04316f39d10d012',
    messagingSenderId: '701813741399',
    projectId: 'neurobridge-2d085',
    authDomain: 'neurobridge-2d085.firebaseapp.com',
    storageBucket: 'neurobridge-2d085.firebasestorage.app',
    measurementId: 'G-2WYN8DS6X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXhIdoytuSDfZy7PAZWfVtnjrTM1DFW8Q',
    appId: '1:701813741399:android:80c9009dd03d2dce10d012',
    messagingSenderId: '701813741399',
    projectId: 'neurobridge-2d085',
    storageBucket: 'neurobridge-2d085.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYgqaVx65982qKSYD5-85FQpbh89DfsWM',
    appId: '1:701813741399:ios:f5cb319edd64490d10d012',
    messagingSenderId: '701813741399',
    projectId: 'neurobridge-2d085',
    storageBucket: 'neurobridge-2d085.firebasestorage.app',
    iosBundleId: 'com.example.udaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYgqaVx65982qKSYD5-85FQpbh89DfsWM',
    appId: '1:701813741399:ios:f5cb319edd64490d10d012',
    messagingSenderId: '701813741399',
    projectId: 'neurobridge-2d085',
    storageBucket: 'neurobridge-2d085.firebasestorage.app',
    iosBundleId: 'com.example.udaan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoMsFF09fuhCdTNjIRYLHq4NUYxzeq3Wg',
    appId: '1:701813741399:web:d9509a981515995910d012',
    messagingSenderId: '701813741399',
    projectId: 'neurobridge-2d085',
    authDomain: 'neurobridge-2d085.firebaseapp.com',
    storageBucket: 'neurobridge-2d085.firebasestorage.app',
    measurementId: 'G-4ZQJERB58T',
  );
}
